## Imports

In [83]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

## Reading the dataset

In [10]:
data=pd.read_csv("creditcard.csv")
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

## Data Information

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

## Data Preprocessing

#### Handling Missing Values

In [8]:
data.isnull().sum()  #data doesnot contain null values

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

#### Data Distribution

In [12]:
data['Class'].value_counts()  #it is a unbalanced data since more than 70% of values are of a particular type

0    284315
1       492
Name: Class, dtype: int64

In [26]:
#seperating the true and false transaction
#0: True Transactions
#1: False Transaction

true_tr=data[data['Class']==0]
false_tr=data[data['Class']==1]

In [27]:
print(true_tr.shape)
print(false_tr.shape)

(284315, 31)
(492, 31)

In [30]:
#statistical measure of the data
true_tr['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [31]:
false_tr['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [34]:
#comparing the mean values of the two type of transaction
data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

## Data Sampling

We will begin doing the undersampling of the given dataset which means building a sample dataset containing similar distribution of true_transaction and false transaction
Number of false_transaction=492

In [36]:
true_tr=true_tr.sample(492)

Concatenation of two dataset

In [39]:
new_data=pd.concat([true_tr,false_tr],axis=0)

In [44]:
new_data['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

#### Feature Selection

In [45]:
X=new_data.drop(columns='Class')
Y=new_data['Class']

In [46]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
226991,144890.0,1.860520,-0.360764,-2.139104,0.338820,0.360428,-0.687449,0.243328,-0.237586,1.132126,...,0.072531,-0.245149,-0.722009,-0.044488,-1.121519,0.019372,-0.038032,-0.032866,-0.011399,130.54
222707,143084.0,-5.996996,4.636881,-3.024911,-0.698902,-3.778382,-1.083890,-3.240884,4.424577,0.431577,...,0.072125,0.346125,0.537689,0.261402,0.003764,0.619630,0.696497,0.059677,0.075715,14.68
164356,116658.0,-1.078105,2.042685,-1.621910,-0.057767,1.660508,-1.136981,-1.360860,-2.233958,-0.742738,...,0.567169,-0.983376,1.092907,-1.483751,-0.576247,-0.803353,-0.182734,0.407153,0.349698,1.00
176488,122790.0,1.954110,-0.374191,-2.708374,-0.516660,2.323616,3.356789,-0.693649,0.871890,0.607078,...,-0.038577,-0.099069,-0.298914,0.230220,0.630836,-0.222937,0.419005,-0.024426,-0.031053,35.60
157919,110617.0,-1.262715,-1.069360,0.238960,-1.787930,0.224797,0.095661,2.104827,-0.555286,0.094273,...,0.393296,0.044849,0.238070,0.502825,0.167480,0.756640,-0.275461,-0.257324,-0.080685,410.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [47]:
Y

226991    0
222707    0
164356    0
176488    0
157919    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

#### Train Test Split

In [48]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [49]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
100623,67571.0,-0.758469,-0.045410,-0.168438,-1.313275,-1.901763,0.739433,3.071892,-0.483422,0.618203,...,-0.032500,0.042619,0.397224,0.072229,-0.242276,0.560916,-0.540955,0.150606,-0.117140,549.06
68195,52875.0,1.021574,0.566806,0.136015,2.342706,0.871043,1.012957,0.245299,0.288700,-1.116011,...,-0.305764,0.126991,0.504324,0.062830,-0.620984,0.377004,0.176194,0.033155,-0.001151,2.17
245564,152808.0,-1.041680,1.285555,0.562956,1.239778,-1.585190,0.399944,-1.090915,0.826169,0.114240,...,-0.129047,0.416882,0.947339,0.252603,0.137703,-1.868254,0.340426,-0.684806,0.110914,35.29
135686,81357.0,-1.469161,0.932708,0.480071,-0.007907,-0.093248,-0.365951,0.547577,0.325915,0.207010,...,0.179320,-0.375914,-0.814273,-0.066784,-0.361462,-0.146461,0.110890,0.257640,-0.121454,89.99
145102,86632.0,-1.140560,0.160451,-1.409791,0.534925,0.264054,-0.703066,3.658121,-0.840094,-0.892395,...,1.450037,0.293274,0.271499,0.767098,-0.295876,0.668837,-0.415864,-0.177273,0.018810,554.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65915,51802.0,1.025564,-0.764294,0.774744,0.436418,-0.913982,0.695525,-0.889122,0.382981,-0.898575,...,-0.489704,-0.101405,0.026066,0.006052,-0.356113,0.146941,-0.262051,0.077499,0.031947,86.00
6740,8463.0,-1.659875,0.386499,3.934998,3.211911,0.214577,2.377242,-0.945849,0.306652,2.449614,...,0.572269,-0.281458,1.001948,-0.549951,-0.259485,0.092977,0.491857,0.329631,-0.278994,1.67
223618,143456.0,-2.006582,3.676577,-5.463811,7.232058,-1.627859,-0.996755,-4.299833,2.268867,-3.651067,...,0.474414,0.713907,-0.063868,0.167947,-0.449864,0.023702,0.536905,0.485864,-0.042393,1.00
43061,41353.0,-15.020981,8.075240,-16.298091,5.664820,-11.918153,-4.246957,-14.716668,9.435084,-6.795398,...,-0.995787,2.525115,-0.832074,-0.186117,0.429781,0.697103,0.056031,-1.310888,-0.707403,34.12
5224,5025.0,-0.729139,0.672145,2.218663,-0.311101,0.531476,-0.761017,0.775887,-0.279836,0.908056,...,-0.033120,-0.394793,-0.886235,0.098135,0.308084,-0.413549,-0.107251,-0.156521,-0.120012,14.46

## Model Training-Logistic Regression

In [56]:
lr=make_pipeline(StandardScaler(),LogisticRegression())
lr.fit(X_train,Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

## Model Evaluation

In [71]:
#on training Data
Y_pred=lr.predict(X_train)
Model_Accuracy=accuracy_score(Y_train,Y_pred)
Model_precision=precision_score(Y_train,Y_pred)
Model_recall=recall_score(Y_train,Y_pred)
Model_F1_score=f1_score(Y_train,Y_pred)

In [72]:
print("Accuracy:",Model_Accuracy)

Accuracy: 0.9504447268106735

In [73]:
print("Precision:",Model_precision)

Precision: 0.9758713136729222

In [74]:
print("Recall:",Model_recall)

Recall: 0.9238578680203046

In [68]:
print("F1_Score",Model_F1_score)

F1_Score 0.9297297297297297

In [77]:
#on testing Data
Y_pred=lr.predict(X_test)
Model_Accuracy=accuracy_score(Y_test,Y_pred)
Model_precision=precision_score(Y_test,Y_pred)
Model_recall=recall_score(Y_test,Y_pred)
Model_F1_score=f1_score(Y_test,Y_pred)

In [78]:
print("Accuracy:",Model_Accuracy)

Accuracy: 0.934010152284264

In [79]:
print("Precision:",Model_precision)

Precision: 0.9885057471264368

In [80]:
print("Recall:",Model_recall)

Recall: 0.8775510204081632

In [81]:
print("F1_Score",Model_F1_score)

F1_Score 0.9297297297297297

## Cross Validation

In [91]:
Accuracy=cross_val_score(lr,X,Y,cv=10,scoring='accuracy')

In [92]:
Accuracy

array([0.94949495, 0.98989899, 0.96969697, 0.86868687, 0.86734694,
       0.94897959, 0.97959184, 0.90816327, 0.95918367, 0.89795918])

In [94]:
F1=cross_val_score(lr,X,Y,cv=10,scoring='f1')

In [95]:
F1

array([0.94845361, 0.98969072, 0.97087379, 0.85714286, 0.85714286,
       0.94736842, 0.97916667, 0.90526316, 0.95833333, 0.88888889])

In [102]:
recall=cross_val_score(lr,X,Y,cv=10,scoring='recall')

In [103]:
recall

array([0.93877551, 0.97959184, 1.        , 0.78      , 0.79591837,
       0.91836735, 0.95918367, 0.87755102, 0.93877551, 0.81632653])

In [104]:
precision=cross_val_score(lr,X,Y,cv=10,scoring='precision')

In [105]:
precision

array([0.95833333, 1.        , 0.94339623, 0.95121951, 0.92857143,
       0.97826087, 1.        , 0.93478261, 0.9787234 , 0.97560976])